###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Bad",
  "content": "News"
}

###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Bad",
  "content": "News"
}

###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Good",
  "content": "News"
}

###
PUT http://localhost:8080/api/v1/posts/2
Content-Type: application/json

{
  "title": "Good News",
  "content": "Everyone"
}

###
DELETE http://localhost:8080/api/v1/posts/1
Content-Type: application/json

###
GET http://localhost:8080/api/v1/posts
Content-Type: application/json

###
GET http://localhost:8080/api/v1/posts/2
Content-Type: application/json


###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": 1,
  "title": "News",
  "content": "Good"
}


###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": 2,
  "title": "News",
  "content": "Good"
}


###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": 3,
  "title": "News",
  "content": "Good"
}



###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": 4,
  "title": "News",
  "content": "Bad"
}


###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "id": 6,
  "title": "Good News everyone",
  "content": "task #1 is done"
}

###
