spring:
  datasource:
    url: jdbc:postgresql://ec2-44-193-111-218.compute-1.amazonaws.com:5432/d50vsr124snblf
    username: svqyiqncrxxfam
    password: c267d7e57fd43e897fa43ba936e0a1c97eb6f8c5890cb5918c3395ca4101da70
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace